apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  name: maproles.aws-auth.samba.tv
spec:
  group: aws-auth.samba.tv
  names:
    kind: MapRole
    listKind: MapRoleList
    plural: maproles
    singular: maprole
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.rolearn
      name: Role ARN
      type: string
    - jsonPath: .spec.groups
      name: Groups
      type: string
    - jsonPath: .spec.email
      name: Email
      type: string
    - jsonPath: .spec.description
      name: Description
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: MapRole is the Schema for the MapRole API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MapRoleSpec defines the desired state of MapRole
            properties:
              description:
                description: A useful description of the MapRole
                type: string
              email:
                description: The email address of a contact person for the MapUser
                type: string
              groups:
                description: The Kubernetes groups to associate with the MapRole
                items:
                  type: string
                type: array
              rolearn:
                description: The Role ARN to associate with the MapRole
                type: string
            required:
            - rolearn
            type: object
          status:
            description: MapRoleStatus defines the observed state of MapRole
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
